# Docker compose YAML file to start an elk container
elk:
  image: sebp/elk:latest
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    # mount the dfds project's elk dir as /data on the container
    # CHANGE THIS to point to where you've downloaded https://github.com/Archethought/dfds/tree/master/elk
    # format LOCAL:CONTAINER, so change LOCAL, leave :/data
    - ~/dev/projects/data/dfds/elk:/data

